"use client";

import { useI18n } from "@/i18n/client";

type PolicyKey = "privacy" | "cookies" | "terms" | "refunds" | "aiSafety" | "medical";

type PolicyContent = {
  title: string;
  intro: string;
  sections: Array<[string, string]>;
};

const content: Record<string, Record<PolicyKey, PolicyContent>> = {
  en: {
    privacy: {
      title: "Privacy Policy",
      intro: "This policy explains what personal data we collect, why we process it, how long we keep it, and how you can exercise your rights when using ShapeAI.",
      sections: [
        ["Data we collect", "We collect account, contact, payment, transaction, usage, support, device, and dietary information needed to provide and improve the service."],
        ["How we use data", "We use data to operate accounts, process token purchases, generate plans, provide support, prevent fraud, meet legal duties, and improve service quality."],
        ["AI processing", "Meal plans are generated by AI using the preferences you provide. You may contact support if you want a human review of an output."],
        ["Sharing and transfers", "We use trusted providers for hosting, payments, email, analytics, customer support, and AI processing. Where data is transferred internationally, appropriate safeguards are used."],
        ["Your rights", "You may request access, correction, deletion, restriction, portability, objection, or consent withdrawal by contacting info@shapeai.co.uk."],
        ["Security and retention", "We use technical and organisational controls to protect data and retain it only for as long as needed for service, legal, audit, and dispute purposes."],
      ],
    },
    cookies: {
      title: "Cookie Policy",
      intro: "This policy explains how ShapeAI uses cookies, localStorage, sessionStorage, pixels, and similar technologies.",
      sections: [
        ["Essential cookies", "Required cookies support login, security, checkout, fraud prevention, and core service operation."],
        ["Functional cookies", "Functional storage remembers preferences such as selected language, currency, and interface settings."],
        ["Analytics and diagnostics", "With consent where required, analytics and diagnostics help us understand usage, errors, and AI quality."],
        ["Marketing cookies", "Marketing or campaign cookies are used only where permitted and can be rejected through cookie controls."],
        ["Managing consent", "You can manage or remove cookies through the cookie banner, footer controls where available, or your browser settings."],
      ],
    },
    terms: {
      title: "Terms and Conditions",
      intro: "These terms govern your access to and use of ShapeAI, including accounts, tokens, AI-generated plans, PDFs, and related services.",
      sections: [
        ["Eligibility", "You must be at least 18 years old and provide accurate account information. You are responsible for account security."],
        ["Tokens and pricing", "Tokens are virtual credits used inside ShapeAI. Before generation, the service displays the token breakdown and total cost."],
        ["Payments", "Payments are handled by third-party processors. Tokens are credited after successful payment or, in test mode, after immediate internal crediting."],
        ["AI outputs", "AI meal plans are generated from your inputs and are not medical advice. You are responsible for reviewing suitability."],
        ["Acceptable use", "Do not abuse the service, attempt unauthorised access, reverse-engineer the platform, or use outputs for unlawful purposes."],
        ["Liability", "The service is provided with reasonable care, but we do not guarantee specific health, fitness, or weight-loss outcomes."],
      ],
    },
    refunds: {
      title: "Refund and Return Policy",
      intro: "This policy explains how refund requests are handled for tokens and digital services.",
      sections: [
        ["Refund requests", "Contact info@shapeai.co.uk with your order or generation reference, account email, issue description, and supporting evidence."],
        ["Unused tokens", "Unused purchased tokens may be refundable before redemption, subject to payment processor fees and legal requirements."],
        ["Redeemed tokens", "Redeemed tokens are generally non-refundable unless a system error prevented delivery, the output was materially defective, or a refund is required by law."],
        ["Processing times", "We aim to acknowledge requests within 5 business days and process approved refunds within 5-10 business days."],
        ["Fraud and abuse", "We may refuse refunds and suspend accounts where fraud, abuse, or chargeback misuse is detected."],
      ],
    },
    aiSafety: {
      title: "AI Use & Safety Policy",
      intro: "This policy explains how ShapeAI uses AI and what safeguards and limitations apply.",
      sections: [
        ["Transparency", "ShapeAI discloses when AI is used to generate meal plans, recipe suggestions, shopping lists, and PDFs."],
        ["Human control", "You choose what to generate and remain responsible for reviewing, editing, using, or ignoring AI suggestions."],
        ["Safety limits", "We apply safeguards to reduce harmful or medically unsafe outputs, but no AI system can prevent every issue."],
        ["What AI can do", "AI can organise meals by calories and macros, suggest substitutions, create shopping lists, and explain recipes."],
        ["What AI cannot do", "AI cannot diagnose conditions, prescribe medication, replace clinicians, or guarantee weight-loss outcomes."],
      ],
    },
    medical: {
      title: "Medical & Nutrition Disclaimer",
      intro: "ShapeAI provides general nutrition and meal-planning information. It is not medical advice and does not replace professional diagnosis or treatment.",
      sections: [
        ["Consult a professional", "Speak with your GP, dietitian, or qualified clinician before changing diet or calorie targets if you have medical conditions, are pregnant or breastfeeding, take medication, or have a history of eating disorders."],
        ["Prescription treatments", "ShapeAI does not prescribe, sell, or promote prescription-only medicines. GLP-1 references are informational only."],
        ["Allergens and suitability", "Always verify ingredients, allergens, intolerances, and portion suitability before following a generated plan."],
        ["Results vary", "We do not guarantee any specific weight-loss amount, health outcome, or time frame."],
        ["Emergency", "In an emergency, call 999 or your local emergency number immediately."],
      ],
    },
  },
  es: {
    privacy: {
      title: "Política de privacidad",
      intro: "Esta política explica qué datos personales recopilamos, por qué los procesamos, cuánto tiempo los conservamos y cómo puedes ejercer tus derechos al usar ShapeAI.",
      sections: [
        ["Datos que recopilamos", "Recopilamos datos de cuenta, contacto, pago, transacciones, uso, soporte, dispositivo y dieta necesarios para prestar y mejorar el servicio."],
        ["Cómo usamos los datos", "Usamos los datos para operar cuentas, procesar compras de tokens, generar planes, prestar soporte, prevenir fraude, cumplir obligaciones legales y mejorar la calidad."],
        ["Procesamiento con IA", "Los planes se generan con IA usando las preferencias que proporcionas. Puedes contactar con soporte si deseas revisión humana de un resultado."],
        ["Compartición y transferencias", "Usamos proveedores de hosting, pagos, correo, analítica, soporte e IA. Cuando hay transferencias internacionales, aplicamos salvaguardas adecuadas."],
        ["Tus derechos", "Puedes solicitar acceso, corrección, eliminación, restricción, portabilidad, oposición o retirada del consentimiento escribiendo a info@shapeai.co.uk."],
        ["Seguridad y conservación", "Usamos controles técnicos y organizativos y conservamos los datos solo el tiempo necesario para servicio, requisitos legales, auditoría y disputas."],
      ],
    },
    cookies: {
      title: "Política de cookies",
      intro: "Esta política explica cómo ShapeAI usa cookies, localStorage, sessionStorage, píxeles y tecnologías similares.",
      sections: [
        ["Cookies esenciales", "Las cookies necesarias permiten inicio de sesión, seguridad, pago, prevención de fraude y funcionamiento básico."],
        ["Cookies funcionales", "El almacenamiento funcional recuerda preferencias como idioma, moneda y ajustes de interfaz."],
        ["Analítica y diagnóstico", "Con consentimiento cuando sea necesario, la analítica y el diagnóstico ayudan a entender uso, errores y calidad de IA."],
        ["Cookies de marketing", "Las cookies de marketing o campañas se usan solo cuando está permitido y pueden rechazarse."],
        ["Gestionar consentimiento", "Puedes gestionar o eliminar cookies mediante el banner, controles del pie cuando estén disponibles o la configuración del navegador."],
      ],
    },
    terms: {
      title: "Términos y condiciones",
      intro: "Estos términos regulan el acceso y uso de ShapeAI, incluidas cuentas, tokens, planes generados por IA, PDF y servicios relacionados.",
      sections: [
        ["Elegibilidad", "Debes tener al menos 18 años y proporcionar datos de cuenta exactos. Eres responsable de la seguridad de tu cuenta."],
        ["Tokens y precios", "Los tokens son créditos virtuales usados en ShapeAI. Antes de generar, el servicio muestra el desglose y coste total."],
        ["Pagos", "Los pagos son gestionados por procesadores externos. Los tokens se acreditan tras pago correcto o, en modo de prueba, tras acreditación interna inmediata."],
        ["Resultados de IA", "Los planes de IA se generan desde tus datos y no son consejo médico. Debes revisar su idoneidad."],
        ["Uso aceptable", "No abuses del servicio, intentes acceso no autorizado, ingeniería inversa ni uses resultados con fines ilegales."],
        ["Responsabilidad", "El servicio se presta con cuidado razonable, pero no garantizamos resultados concretos de salud, fitness o pérdida de peso."],
      ],
    },
    refunds: {
      title: "Política de reembolsos y devoluciones",
      intro: "Esta política explica cómo se gestionan solicitudes de reembolso para tokens y servicios digitales.",
      sections: [
        ["Solicitudes", "Contacta con info@shapeai.co.uk con referencia de pedido o generación, email de cuenta, descripción y pruebas."],
        ["Tokens no usados", "Los tokens comprados y no usados pueden ser reembolsables antes de canjearse, sujetos a comisiones y ley aplicable."],
        ["Tokens canjeados", "Los tokens canjeados normalmente no son reembolsables salvo error del sistema, resultado defectuoso o exigencia legal."],
        ["Plazos", "Intentamos acusar recibo en 5 días laborables y procesar reembolsos aprobados en 5-10 días laborables."],
        ["Fraude y abuso", "Podemos rechazar reembolsos y suspender cuentas si detectamos fraude, abuso o uso indebido de contracargos."],
      ],
    },
    aiSafety: {
      title: "Política de uso y seguridad de IA",
      intro: "Esta política explica cómo ShapeAI usa IA y qué salvaguardas y limitaciones se aplican.",
      sections: [
        ["Transparencia", "ShapeAI informa cuando se usa IA para generar planes, recetas, listas de compra y PDF."],
        ["Control humano", "Tú decides qué generar y eres responsable de revisar, editar, usar o ignorar sugerencias."],
        ["Límites de seguridad", "Aplicamos salvaguardas para reducir resultados dañinos o médicamente inseguros, pero ningún sistema de IA evita todos los problemas."],
        ["Qué puede hacer la IA", "La IA puede organizar comidas por calorías y macros, sugerir sustituciones, crear listas y explicar recetas."],
        ["Qué no puede hacer", "La IA no diagnostica, no prescribe, no reemplaza a profesionales ni garantiza pérdida de peso."],
      ],
    },
    medical: {
      title: "Descargo médico y nutricional",
      intro: "ShapeAI proporciona información general sobre nutrición y planificación de comidas. No es consejo médico ni sustituye diagnóstico o tratamiento profesional.",
      sections: [
        ["Consulta a un profesional", "Habla con tu médico, dietista o clínico antes de cambiar dieta o calorías si tienes condiciones médicas, embarazo, lactancia, medicación o historial de trastornos alimentarios."],
        ["Tratamientos con receta", "ShapeAI no prescribe, vende ni promociona medicamentos con receta. Las referencias a GLP-1 son solo informativas."],
        ["Alérgenos e idoneidad", "Verifica siempre ingredientes, alérgenos, intolerancias y porciones antes de seguir un plan."],
        ["Los resultados varían", "No garantizamos pérdida de peso, resultado de salud ni plazo específico."],
        ["Emergencia", "En una emergencia, llama al 999 o a tu número local de emergencias inmediatamente."],
      ],
    },
  },
  de: {
    privacy: {
      title: "Datenschutzerklärung",
      intro: "Diese Richtlinie erklärt, welche personenbezogenen Daten wir erfassen, warum wir sie verarbeiten, wie lange wir sie aufbewahren und wie du deine Rechte bei der Nutzung von ShapeAI ausüben kannst.",
      sections: [["Erfasste Daten", "Wir erfassen Konto-, Kontakt-, Zahlungs-, Transaktions-, Nutzungs-, Support-, Geräte- und Ernährungsdaten, die für Bereitstellung und Verbesserung nötig sind."], ["Verwendung", "Wir nutzen Daten für Konten, Tokenkäufe, Plangenerierung, Support, Betrugsprävention, rechtliche Pflichten und Qualitätsverbesserung."], ["KI-Verarbeitung", "Pläne werden mit KI aus deinen Präferenzen erstellt. Du kannst den Support kontaktieren, wenn du eine menschliche Prüfung möchtest."], ["Weitergabe und Transfers", "Wir nutzen vertrauenswürdige Anbieter für Hosting, Zahlungen, E-Mail, Analytik, Support und KI. Bei internationalen Transfers gelten geeignete Schutzmaßnahmen."], ["Deine Rechte", "Du kannst Zugang, Berichtigung, Löschung, Einschränkung, Portabilität, Widerspruch oder Widerruf der Einwilligung unter info@shapeai.co.uk beantragen."], ["Sicherheit und Aufbewahrung", "Wir nutzen technische und organisatorische Kontrollen und speichern Daten nur so lange wie für Service, Recht, Audit und Streitfälle nötig."]],
    },
    cookies: { title: "Cookie-Richtlinie", intro: "Diese Richtlinie erklärt, wie ShapeAI Cookies, localStorage, sessionStorage, Pixel und ähnliche Technologien nutzt.", sections: [["Essenzielle Cookies", "Notwendige Cookies unterstützen Login, Sicherheit, Checkout, Betrugsprävention und Kernfunktionen."], ["Funktionale Cookies", "Funktionaler Speicher merkt sich Sprache, Währung und Oberflächeinstellungen."], ["Analytik und Diagnose", "Mit Einwilligung, wo erforderlich, helfen Analytik und Diagnose bei Nutzung, Fehlern und KI-Qualität."], ["Marketing-Cookies", "Marketing- oder Kampagnen-Cookies werden nur erlaubt eingesetzt und können abgelehnt werden."], ["Einwilligung verwalten", "Du kannst Cookies über Banner, Footer-Kontrollen oder Browsereinstellungen verwalten oder löschen."]] },
    terms: { title: "Allgemeine Geschäftsbedingungen", intro: "Diese Bedingungen regeln Zugang und Nutzung von ShapeAI, einschließlich Konten, Tokens, KI-Plänen, PDFs und verbundenen Diensten.", sections: [["Berechtigung", "Du musst mindestens 18 Jahre alt sein und korrekte Kontodaten angeben. Du bist für Kontosicherheit verantwortlich."], ["Tokens und Preise", "Tokens sind virtuelle Guthaben in ShapeAI. Vor der Erstellung zeigt der Dienst Aufschlüsselung und Gesamtkosten."], ["Zahlungen", "Zahlungen laufen über externe Anbieter. Tokens werden nach erfolgreicher Zahlung oder im Testmodus sofort intern gutgeschrieben."], ["KI-Ausgaben", "KI-Pläne entstehen aus deinen Eingaben und sind keine medizinische Beratung. Du musst die Eignung prüfen."], ["Zulässige Nutzung", "Missbrauche den Dienst nicht, versuche keinen unbefugten Zugriff, kein Reverse Engineering und keine rechtswidrige Nutzung."], ["Haftung", "Der Dienst wird mit angemessener Sorgfalt bereitgestellt, aber wir garantieren keine bestimmten Gesundheits-, Fitness- oder Abnehmergebnisse."]] },
    refunds: { title: "Rückerstattungs- und Rückgaberichtlinie", intro: "Diese Richtlinie erklärt, wie Rückerstattungen für Tokens und digitale Dienste behandelt werden.", sections: [["Anfragen", "Kontaktiere info@shapeai.co.uk mit Bestell- oder Generierungsreferenz, Konto-E-Mail, Problembeschreibung und Nachweisen."], ["Ungenutzte Tokens", "Ungenutzte gekaufte Tokens können vor Einlösung erstattungsfähig sein, vorbehaltlich Gebühren und geltendem Recht."], ["Eingelöste Tokens", "Eingelöste Tokens sind meist nicht erstattungsfähig, außer bei Systemfehler, mangelhaftem Ergebnis oder gesetzlicher Pflicht."], ["Bearbeitungszeiten", "Wir bestätigen Anfragen möglichst binnen 5 Werktagen und bearbeiten genehmigte Erstattungen binnen 5-10 Werktagen."], ["Betrug und Missbrauch", "Wir können Erstattungen ablehnen und Konten sperren, wenn Betrug, Missbrauch oder Chargeback-Missbrauch erkannt wird."]] },
    aiSafety: { title: "KI-Nutzung und Sicherheit", intro: "Diese Richtlinie erklärt, wie ShapeAI KI nutzt und welche Schutzmaßnahmen und Grenzen gelten.", sections: [["Transparenz", "ShapeAI weist darauf hin, wenn KI für Pläne, Rezepte, Einkaufslisten und PDFs genutzt wird."], ["Menschliche Kontrolle", "Du entscheidest, was erstellt wird, und bist für Prüfen, Bearbeiten, Verwenden oder Ignorieren verantwortlich."], ["Sicherheitsgrenzen", "Wir nutzen Schutzmaßnahmen gegen schädliche oder medizinisch unsichere Inhalte, aber kein KI-System verhindert alle Probleme."], ["Was KI kann", "KI kann Mahlzeiten nach Kalorien und Makros organisieren, Alternativen vorschlagen, Listen erstellen und Rezepte erklären."], ["Was KI nicht kann", "KI diagnostiziert nicht, verschreibt keine Medikamente, ersetzt keine Fachpersonen und garantiert keinen Gewichtsverlust."]] },
    medical: { title: "Medizinischer und Ernährungshinweis", intro: "ShapeAI bietet allgemeine Informationen zu Ernährung und Mahlzeitenplanung. Es ist keine medizinische Beratung und ersetzt keine professionelle Diagnose oder Behandlung.", sections: [["Fachperson konsultieren", "Sprich mit Arzt, Ernährungsberater oder Klinik, bevor du Ernährung oder Kalorien änderst, wenn du Erkrankungen hast, schwanger bist, stillst, Medikamente nimmst oder Essstörungen hattest."], ["Verschreibungspflichtige Behandlungen", "ShapeAI verschreibt, verkauft oder bewirbt keine verschreibungspflichtigen Medikamente. GLP-1-Hinweise sind nur informativ."], ["Allergene und Eignung", "Prüfe immer Zutaten, Allergene, Unverträglichkeiten und Portionsgrößen, bevor du einem Plan folgst."], ["Ergebnisse variieren", "Wir garantieren keinen bestimmten Gewichtsverlust, gesundheitlichen Effekt oder Zeitrahmen."], ["Notfall", "Rufe im Notfall sofort 999 oder deine lokale Notrufnummer an."]] },
  },
};

export function LocalizedPolicyPage({ policy }: { policy: PolicyKey }) {
  const { locale } = useI18n();
  const page = content[locale]?.[policy] ?? content.en[policy];

  return (
    <main className="mx-auto max-w-4xl px-4 py-10">
      <article className="rounded-3xl border border-neutral-lines bg-white p-6 shadow-soft md:p-10">
        <p className="mb-3 text-sm font-semibold uppercase tracking-[0.18em] text-accent">ShapeAI</p>
        <h1 className="font-headings text-3xl font-semibold text-neutral-ink md:text-4xl">{page.title}</h1>
        <p className="mt-4 text-neutral-slate">{page.intro}</p>
        <div className="mt-8 space-y-6">
          {page.sections.map(([title, body], index) => (
            <section key={title}>
              <h2 className="font-headings text-xl font-semibold text-neutral-ink">{index + 1}. {title}</h2>
              <p className="mt-2 text-neutral-slate">{body}</p>
            </section>
          ))}
        </div>
        <div className="mt-8 rounded-2xl bg-neutral-lines/20 p-5 text-sm text-neutral-slate">
          <p><strong>PREPARING BUSINESS LTD</strong></p>
          <p>Company no.: 16107292</p>
          <p>12 Skinner Lane, Leeds, England, LS7 1DL</p>
          <p>info@shapeai.co.uk | +44 7463 585216</p>
        </div>
      </article>
    </main>
  );
}
